"""add_preferred_provider

Revision ID: 10cffc244899
Revises: b603412c3f5c
Create Date: 2026-07-20 13:30:50.192173+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10cffc244899'
down_revision: Union[str, None] = 'b603412c3f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('preferred_provider', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'preferred_provider')
    # ### end Alembic commands ###
