"""better_auth_schema

Revision ID: b603412c3f5c
Revises: 0006_rag_pgvector
Create Date: 2026-07-20 13:27:11.529073+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b603412c3f5c'
down_revision: Union[str, None] = '0006_rag_pgvector'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('emailVerified', sa.Boolean(), nullable=False),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    
    # Data migration: copy old users into the new user table before we recreate foreign keys
    op.execute(
        """
        INSERT INTO "user" (id, name, email, "emailVerified", "createdAt", "updatedAt")
        SELECT id, split_part(email, '@', 1), email, true, created_at, created_at FROM users;
        """
    )
    op.create_table('verification',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Text(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('accountId', sa.Text(), nullable=False),
    sa.Column('providerId', sa.Text(), nullable=False),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.Column('accessToken', sa.Text(), nullable=True),
    sa.Column('refreshToken', sa.Text(), nullable=True),
    sa.Column('idToken', sa.Text(), nullable=True),
    sa.Column('accessTokenExpiresAt', sa.DateTime(), nullable=True),
    sa.Column('refreshTokenExpiresAt', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('password', sa.Text(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.Column('ipAddress', sa.Text(), nullable=True),
    sa.Column('userAgent', sa.Text(), nullable=True),
    sa.Column('userId', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )

    op.alter_column('conversations', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('conversations_user_id_fkey'), 'conversations', type_='foreignkey')
    op.create_foreign_key(None, 'conversations', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_chunks_embedding_hnsw'), table_name='document_chunks', postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.alter_column('documents', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('documents_user_id_fkey'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_api_keys', 'user_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.Text(),
               existing_nullable=False)
    op.drop_constraint(op.f('user_api_keys_user_id_fkey'), 'user_api_keys', type_='foreignkey')
    op.create_foreign_key(None, 'user_api_keys', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_api_keys', type_='foreignkey')
    op.create_foreign_key(op.f('user_api_keys_user_id_fkey'), 'user_api_keys', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_api_keys', 'user_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_user_id_fkey'), 'documents', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('documents', 'user_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_document_chunks_embedding_hnsw'), 'document_chunks', ['embedding'], unique=False, postgresql_ops={'embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.create_foreign_key(op.f('conversations_user_id_fkey'), 'conversations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('conversations', 'user_id',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=36),
               existing_nullable=False)
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('preferred_provider', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_table('session')
    op.drop_table('account')
    op.drop_table('verification')
    op.drop_table('user')
    # ### end Alembic commands ###
